# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20161117_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profesion',
        ),
    ]
