# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_remove_usuario_profesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interes',
            options={'verbose_name': 'Interés', 'verbose_name_plural': 'Intereses'},
        ),
    ]
