# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20161117_2127'),
        ('Usuario', '0002_auto_20161117_2235'),
    ]

    operations = [
    ]
