# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_auto_20161115_2106'),
        ('Usuario', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_usuario', to='direcciones.Direccion', verbose_name='direccion'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='direcciones.Telefono', verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
