# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_auto_20161115_2106'),
        ('Usuario', '0007_interes_es_en_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='_direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_usuario', to='direcciones.Direccion', verbose_name='direccion'),
        ),
    ]
