# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuestionario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(choices=[('Texto', 'Texto'), ('Booleno', 'Boolean')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_Bool', models.BooleanField(max_length=20)),
                ('respuesta_Single', models.CharField(max_length=200)),
                ('relacion_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuesta.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuesta.Pregunta'),
        ),
    ]
