# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='enunciado',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta',
            field=models.ManyToManyField(to='Encuesta.Pregunta'),
        ),
    ]
