# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuesta', '0002_auto_20161115_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_Single',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
