# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 09:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(default=b'', max_length=11)),
                ('nombre', models.CharField(default=b'', max_length=300, verbose_name=b'Colonia')),
                ('municipio', models.CharField(default=b'', max_length=60, verbose_name=b'Delegacion o municipio')),
                ('ciudad', models.CharField(default=b'', max_length=128, verbose_name=b'Ciudad')),
                ('estado', models.CharField(default=b'DF', max_length=60, verbose_name=b'Estado')),
                ('pais', models.CharField(default=b'Mexico', max_length=300, verbose_name=b'Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('colonia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='direcciones.Colonia')),
                ('slug', models.SlugField(max_length=300)),
                ('calle_y_numero', models.CharField(default=b'', editable=False, max_length=300, verbose_name=b'Calle y numero')),
                ('calle', models.CharField(default=b'', max_length=220, verbose_name=b'Calle')),
                ('numero_exterior', models.CharField(default=b'', max_length=40, verbose_name=b'Numero exterior')),
                ('numero_interior', models.CharField(blank=True, default=b'', max_length=40, verbose_name=b'Numero interior')),
                ('utm_este', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, verbose_name=b'Coordenadas UTM-E')),
                ('utm_norte', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=11, verbose_name=b'Coordenadas UTM-N')),
                ('enlace_mapa', models.URLField(blank=True, default=b'')),
                ('creado_el', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('modificado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
            bases=('direcciones.colonia',),
        ),
    ]
