# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_auto_20161115_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='utm_este',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='utm_norte',
        ),
        migrations.AddField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17, verbose_name='Coordenadas UTM-N'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17, verbose_name='Coordenadas UTM-E'),
        ),
    ]
