# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=140)),
                ('observationTime', models.DateTimeField()),
                ('stationName', models.CharField(max_length=140)),
                ('icao', models.CharField(max_length=40)),
                ('countryCode', models.CharField(max_length=10)),
                ('elevation', models.IntegerField()),
                ('dewPoint', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('cloudsCode', models.CharField(max_length=60)),
                ('weatherCondition', models.CharField(max_length=15)),
                ('hectoPascAltimeter', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('windDirection', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('windSpeed', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('lat', models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17, verbose_name='Coordenadas UTM-E')),
                ('lng', models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17, verbose_name='Coordenadas UTM-E')),
            ],
        ),
    ]
